image:
    file: gitpod.Dockerfile

tasks:
    - name: FRB Codegen
      command: cargo install 'flutter_rust_bridge_codegen@2.0.0-dev.21' && flutter_rust_bridge_codegen generate --watch
    - name: flutter
      command: flutter run
