[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
# Turn on a small amount of optimisation in Development mode.
opt-level = 1

[workspace]
members = ["crates/client", "crates/server", "crates/common"]

resolver = "2"
