[config]
default_to_workspace = false

[env]
CARGO_MAKE_RUN_DEPRECATED_MIGRATION = false


[tasks.frontend-deps]
cwd = "crates/client/frontend"
command = "npm"
args = ["install"]

[tasks.frontend-rel]
cwd = "crates/client/frontend"
command = "npm"
args = ["run", "build"]
dependencies = ["frontend-deps"]

[tasks.release]
command = "cargo"
args = ["build", "--release", "--package", "bramlett"]
dependencies = ["frontend-rel"]

[tasks.frontend-dev]
deprecated = "don't use this manually; use `cargo make dev` instead"
cwd = "crates/client/frontend"
command = "npm"
args = ["run", "dev"]
# needs frontend-deps, but that's dealt with in `tasks.dev`

[tasks.frontend-gql-dev]
deprecated = "don't use this manually; use `cargo make dev` instead"
cwd = "crates/client/frontend"
command = "npm"
args = ["run", "gen:watch"]
# needs frontend-deps, but that's dealt with in `tasks.dev`

[tasks.client-dev]
deprecated = "don't use this manually; use `cargo make dev` instead"
command = "cargo"
args = ["run", "--package", "bramlett"]

[tasks.deploy-server]
cwd = "crates/server"
command = "cargo"
args = ["shuttle", "deploy", "--no-test"]

[tasks.server-dev]
deprecated = "don't use this manually; use `cargo make dev` instead"
cwd = "crates/server"
command = "cargo"
args = ["shuttle", "run"]


[tasks.dev]
run_task = { name = [
    "server-dev",
    "client-dev",
    "frontend-dev",
    "frontend-gql-dev",
], fork = true, parallel = true }
dependencies = ["frontend-deps"]
