[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspc = { version = "0.1.3", features = ["axum"] }
tokio = { version = "1.26.0", features = ["full"] }
async-stream = "0.3.4"
axum = { version = "0.6.10", features = ["ws"] }
tower-http = { version = "0.4.0", default-features = false, features = [
    "cors",
] }
once_cell = "1.18.0"
