[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "811877b", features = [
    "tracing",
    "unstable",
] }
rspc-httpz = { git = "https://github.com/oscartbeaumont/rspc", rev = "811877b", features = [
    "axum",
] }
tokio = { version = "1.33.0", features = ["full"] }
async-stream = "0.3.5"
axum = { version = "0.6.20", features = ["ws", "http2"] }
tower-http = { version = "0.4.4", default-features = false, features = [
    "cors",
] }
futures = "0.3.28"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
thiserror = { version = "1.0" }
serde = { version = "1", default-features = false, features = ["derive"] }
specta = { version = "=2.0.0-rc.6", default-features = false, features = [
    "serde",
    "serde_json",
] }
