[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.16"
reqwest = { version = "0.11.23", default-features = false, features = ["default-tls"] }
serde_json = "1.0.111"
sevenz-rust = "0.5.4"
thiserror = "1.0.56"
uuid = "1.6.1"
