[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.79"
flutter_rust_bridge = "=2.0.0-dev.20"
reqwest = { version = "0.11.23", default-features = false, features = ["default-tls", "json"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
sevenz-rust = "0.5.4"
thiserror = "1.0.56"
tokio = { version = "1.35.1", default-features = false, features = ["fs"] }
uuid = { version = "1.6.1", features = ["serde"] }
