// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Game {
  final String name;
  final String exe;
  final List<String> args;
  final String icon;
  final String url;
  final String uuid;
  final String sha256;
  final GameState state;

  const Game({
    required this.name,
    required this.exe,
    required this.args,
    required this.icon,
    required this.url,
    required this.uuid,
    required this.sha256,
    required this.state,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      exe.hashCode ^
      args.hashCode ^
      icon.hashCode ^
      url.hashCode ^
      uuid.hashCode ^
      sha256.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Game &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          exe == other.exe &&
          args == other.args &&
          icon == other.icon &&
          url == other.url &&
          uuid == other.uuid &&
          sha256 == other.sha256 &&
          state == other.state;
}

enum GameState {
  notInstalled,
  installed,
}

class Games {
  final List<Game> games;

  const Games({
    required this.games,
  });

  @override
  int get hashCode => games.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Games &&
          runtimeType == other.runtimeType &&
          games == other.games;
}
