// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.20.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Games> fetchGames({dynamic hint}) =>
    RustLib.instance.api.fetchGames(hint: hint);

class Games {
  final List<Games> games;

  const Games({
    required this.games,
  });

  @override
  int get hashCode => games.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Games &&
          runtimeType == other.runtimeType &&
          games == other.games;
}
