mutation DeleteGame($game: GameId!) {
	delete(game: $game)
}

mutation DownloadGame($game: GameId!) {
	download(game: $game)
}

mutation RunGame($game: GameId!) {
	run(game: $game)
}

mutation UpdateGames {
	updateGameList
}

mutation LaunchFirefox {
	launchFirefox
}
